/***
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Do not edit this file. It will be overwritten when the configure script is run.
 ***/

#include "cache.h"
#include "champsim.h"
#include "dram_controller.h"
#include "ooo_cpu.h"
#include "ptw.h"
#include "vmem.h"
#include "operable.h"
#include "champsim_constants.h"
#include <array>
#include <vector>
#include "l2c.h"
VirtualMemory vmem(8589934592, 1 << 12, 5, 1, 200);

MEMORY_CONTROLLER DRAM(1.25);
CACHE cpu0_LLC("cpu0_LLC", 1.0, 6, 2048, 16, 32, 32, 32, 64, 19, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, &DRAM, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_LLC("cpu1_LLC", 1.0, 6, 2048, 16, 32, 32, 32, 64, 19, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, &DRAM, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_LLC("cpu2_LLC", 1.0, 6, 2048, 16, 32, 32, 32, 64, 19, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, &DRAM, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_LLC("cpu3_LLC", 1.0, 6, 2048, 16, 32, 32, 32, 64, 19, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, &DRAM, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
L2C cpu0_L2C("cpu0_L2C", 1.0, 5, 1024, 8, 32, 32, 16, 32, 9, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, {&cpu0_LLC,&cpu1_LLC,&cpu2_LLC,&cpu3_LLC}, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
L2C cpu1_L2C("cpu1_L2C", 1.0, 5, 1024, 8, 32, 32, 16, 32, 9, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, {&cpu0_LLC,&cpu1_LLC,&cpu2_LLC,&cpu3_LLC}, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
L2C cpu2_L2C("cpu2_L2C", 1.0, 5, 1024, 8, 32, 32, 16, 32, 9, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, {&cpu0_LLC,&cpu1_LLC,&cpu2_LLC,&cpu3_LLC}, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
L2C cpu3_L2C("cpu3_L2C", 1.0, 5, 1024, 8, 32, 32, 16, 32, 9, 1, 1, 1, LOG2_BLOCK_SIZE, 0, 0, 0, 5, {&cpu0_LLC,&cpu1_LLC,&cpu2_LLC,&cpu3_LLC}, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu0_L1D("cpu0_L1D", 1.0, 4, 64, 12, 64, 64, 8, 16, 4, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 0, 5, &cpu0_L2C, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_L1D("cpu1_L1D", 1.0, 4, 64, 12, 64, 64, 8, 16, 4, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 0, 5, &cpu1_L2C, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_L1D("cpu2_L1D", 1.0, 4, 64, 12, 64, 64, 8, 16, 4, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 0, 5, &cpu2_L2C, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_L1D("cpu3_L1D", 1.0, 4, 64, 12, 64, 64, 8, 16, 4, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 0, 5, &cpu3_L2C, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
PageTableWalker cpu0_PTW("cpu0_PTW", 0, 3, 1, 2, 1, 4, 2, 4, 4, 8, 16, 5, 2, 2, 0, &cpu0_L1D);
PageTableWalker cpu1_PTW("cpu1_PTW", 1, 3, 1, 2, 1, 4, 2, 4, 4, 8, 16, 5, 2, 2, 0, &cpu1_L1D);
PageTableWalker cpu2_PTW("cpu2_PTW", 2, 3, 1, 2, 1, 4, 2, 4, 4, 8, 16, 5, 2, 2, 0, &cpu2_L1D);
PageTableWalker cpu3_PTW("cpu3_PTW", 3, 3, 1, 2, 1, 4, 2, 4, 4, 8, 16, 5, 2, 2, 0, &cpu3_L1D);
CACHE cpu0_STLB("cpu0_STLB", 1.0, 2, 128, 12, 32, 32, 0, 16, 7, 1, 1, 1, LOG2_PAGE_SIZE, 0, 0, 0, 5, &cpu0_PTW, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_STLB("cpu1_STLB", 1.0, 2, 128, 12, 32, 32, 0, 16, 7, 1, 1, 1, LOG2_PAGE_SIZE, 0, 0, 0, 5, &cpu1_PTW, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_STLB("cpu2_STLB", 1.0, 2, 128, 12, 32, 32, 0, 16, 7, 1, 1, 1, LOG2_PAGE_SIZE, 0, 0, 0, 5, &cpu2_PTW, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_STLB("cpu3_STLB", 1.0, 2, 128, 12, 32, 32, 0, 16, 7, 1, 1, 1, LOG2_PAGE_SIZE, 0, 0, 0, 5, &cpu3_PTW, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu0_L1I("cpu0_L1I", 1.0, 1, 64, 8, 64, 64, 32, 8, 3, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 1, 5, &cpu0_L2C, CACHE::pref_t::CPU_REDIRECT_pprefetcherDno_instr_, CACHE::repl_t::rreplacementDlru);
CACHE cpu0_ITLB("cpu0_ITLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 1, 5, &cpu0_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu0_DTLB("cpu0_DTLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 0, 5, &cpu0_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_L1I("cpu1_L1I", 1.0, 1, 64, 8, 64, 64, 32, 8, 3, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 1, 5, &cpu1_L2C, CACHE::pref_t::CPU_REDIRECT_pprefetcherDno_instr_, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_ITLB("cpu1_ITLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 1, 5, &cpu1_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu1_DTLB("cpu1_DTLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 0, 5, &cpu1_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_L1I("cpu2_L1I", 1.0, 1, 64, 8, 64, 64, 32, 8, 3, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 1, 5, &cpu2_L2C, CACHE::pref_t::CPU_REDIRECT_pprefetcherDno_instr_, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_ITLB("cpu2_ITLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 1, 5, &cpu2_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu2_DTLB("cpu2_DTLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 0, 5, &cpu2_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_L1I("cpu3_L1I", 1.0, 1, 64, 8, 64, 64, 32, 8, 3, 1, 2, 2, LOG2_BLOCK_SIZE, 0, 1, 1, 5, &cpu3_L2C, CACHE::pref_t::CPU_REDIRECT_pprefetcherDno_instr_, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_ITLB("cpu3_ITLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 1, 5, &cpu3_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
CACHE cpu3_DTLB("cpu3_DTLB", 1.0, 1, 16, 4, 16, 16, 0, 8, 0, 1, 2, 2, LOG2_PAGE_SIZE, 0, 1, 0, 5, &cpu3_STLB, CACHE::pref_t::pprefetcherDno, CACHE::repl_t::rreplacementDlru);
O3_CPU cpu0(0, 1.0, 32, 8, 16, 64, 32, 32, 352, 128, 72, 6, 6, 6, 128, 4, 2, 2, 5, 1, 1, 1, 0, 0, &cpu0_ITLB, &cpu0_DTLB, &cpu0_L1I, &cpu0_L1D, O3_CPU::bpred_t::bbranchDbimodal, O3_CPU::btb_t::bbtbDbasic_btb, O3_CPU::ipref_t::pprefetcherDno_instr);
O3_CPU cpu1(1, 1.0, 32, 8, 16, 64, 32, 32, 352, 128, 72, 6, 6, 6, 128, 4, 2, 2, 5, 1, 1, 1, 0, 0, &cpu1_ITLB, &cpu1_DTLB, &cpu1_L1I, &cpu1_L1D, O3_CPU::bpred_t::bbranchDbimodal, O3_CPU::btb_t::bbtbDbasic_btb, O3_CPU::ipref_t::pprefetcherDno_instr);
O3_CPU cpu2(2, 1.0, 32, 8, 16, 64, 32, 32, 352, 128, 72, 6, 6, 6, 128, 4, 2, 2, 5, 1, 1, 1, 0, 0, &cpu2_ITLB, &cpu2_DTLB, &cpu2_L1I, &cpu2_L1D, O3_CPU::bpred_t::bbranchDbimodal, O3_CPU::btb_t::bbtbDbasic_btb, O3_CPU::ipref_t::pprefetcherDno_instr);
O3_CPU cpu3(3, 1.0, 32, 8, 16, 64, 32, 32, 352, 128, 72, 6, 6, 6, 128, 4, 2, 2, 5, 1, 1, 1, 0, 0, &cpu3_ITLB, &cpu3_DTLB, &cpu3_L1I, &cpu3_L1D, O3_CPU::bpred_t::bbranchDbimodal, O3_CPU::btb_t::bbtbDbasic_btb, O3_CPU::ipref_t::pprefetcherDno_instr);
std::array<O3_CPU*, NUM_CPUS> ooo_cpu {
&cpu0, &cpu1, &cpu2, &cpu3
};
std::array<CACHE*, NUM_CACHES> caches {
&cpu0_LLC, &cpu1_LLC, &cpu2_LLC, &cpu3_LLC, &cpu0_L2C, &cpu1_L2C, &cpu2_L2C, &cpu3_L2C, &cpu0_L1D, &cpu1_L1D, &cpu2_L1D, &cpu3_L1D, &cpu0_STLB, &cpu1_STLB, &cpu2_STLB, &cpu3_STLB, &cpu0_L1I, &cpu0_ITLB, &cpu0_DTLB, &cpu1_L1I, &cpu1_ITLB, &cpu1_DTLB, &cpu2_L1I, &cpu2_ITLB, &cpu2_DTLB, &cpu3_L1I, &cpu3_ITLB, &cpu3_DTLB
};
std::array<champsim::operable*, NUM_OPERABLES> operables {
&cpu0, &cpu1, &cpu2, &cpu3, &cpu0_LLC, &cpu1_LLC, &cpu2_LLC, &cpu3_LLC, &cpu0_L2C, &cpu1_L2C, &cpu2_L2C, &cpu3_L2C, &cpu0_L1D, &cpu1_L1D, &cpu2_L1D, &cpu3_L1D, &cpu0_PTW, &cpu1_PTW, &cpu2_PTW, &cpu3_PTW, &cpu0_STLB, &cpu1_STLB, &cpu2_STLB, &cpu3_STLB, &cpu0_L1I, &cpu0_ITLB, &cpu0_DTLB, &cpu1_L1I, &cpu1_ITLB, &cpu1_DTLB, &cpu2_L1I, &cpu2_ITLB, &cpu2_DTLB, &cpu3_L1I, &cpu3_ITLB, &cpu3_DTLB, &DRAM
};
